/*
 Problem: https://www.hackerrank.com/challenges/the-company

 Author: Eda AYDIN
 */
 SELECT C.COMPANY_CODE, C.FOUNDER,
        COUNT(DISTINCT L.LEAD_MANAGER_CODE),
        COUNT(DISTINCT S.SENIOR_MANAGER_CODE),
        COUNT(DISTINCT M.MANAGER_CODE),
        COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY AS C,
     LEAD_MANAGER AS L,
     SENIOR_MANAGER AS S,
     MANAGER AS M,
     EMPLOYEE AS E
WHERE C.COMPANY_CODE = L.COMPANY_CODE
AND L.LEAD_MANAGER_CODE = S.LEAD_MANAGER_CODE
AND S.SENIOR_MANAGER_CODE = M.SENIOR_MANAGER_CODE
AND M.MANAGER_CODE = E.MANAGER_CODE
GROUP BY C.COMPANY_CODE, C.FOUNDER
ORDER BY COMPANY_CODE