#!/bin/python3

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    # Initialize the Fibonacci sequence with the first two terms
    fib = [1, 2]
    # Variable to store the sum of even-valued terms
    sum_even = 0

    # Continue generating Fibonacci terms until the last term is less than or equal to n
    while fib[-1] <= n:
        # Check if the current term is even
        if fib[-1] % 2 == 0:
            # Add the even term to the sum
            sum_even += fib[-1]
        # Generate the next Fibonacci term by adding the previous two terms
        fib.append(fib[-1] + fib[-2])
    
    # Print the sum of even-valued terms
    print(sum_even)